[package]
name = "quinn_project"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = { version = "0.11.7", features = ["rustls", "rustls-aws-lc-rs", "rustls-ring"] }
quinn-proto = "0.11.11"
rcgen = "0.13.2"
rustls = "0.23.26"
tokio = { version = "1.44.2", features = ["full"] }


[[bin]]
name = "quinn_server"
path = "src/server/quinn_server.rs"

[[bin]]
name = "quinn_client"
path = "src/client/quinn_client.rs"

[[bin]]
name = "main"
path = "src/main.rs"